import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Sherwin Nofuente",
      email: "shernof@yahoo.com",
      password: bcrypt.hashSync("test1"),
      isAdmin: "true",
    },
    {
      name: "Jedidiah Nofuente",
      email: "jedi@gmail.com",
      password: bcrypt.hashSync("test1"),
      isAdmin: "false",
    },
    {
      name: "Angelyn Nofuente",
      email: "angelyn.nofuente@yahoo.com",
      password: bcrypt.hashSync("test1"),
      isAdmin: "false",
    },
  ],
  products: [
    {
      // _id:'1',
      name: "Nike Slim shirt",
      desc: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg", // 679px × 829px
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 0,
      numReviews: 10,
      detailedDescription: "high quality shirt",
    },
    {
      // _id:'2',
      name: "Adidas Fit Shirt",
      desc: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 3.0,
      numReviews: 10,
      detailedDescription: "high quality product",
    },
    {
      // _id:'3',
      name: "Nike Slim Pant",
      desc: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      detailedDescription: "high quality product",
    },
    {
      // _id:'4',
      name: "Adidas Fit Pant",
      desc: "adidas-fit-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 5,
      numReviews: 10,
      detailedDescription: "high quality product",
    },
  ],
};
export default data;
