const data = {
  products: [
    {
      name: "Nike Slim shirt",
      desc: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg", // 679px × 829px
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 0,
      numReviews: 10,
      detailedDescription: "high quality shirt",
    },
    {
      name: "Adidas Fit Shirt",
      desc: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 3.0,
      numReviews: 10,
      detailedDescription: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      desc: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      detailedDescription: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      desc: "adidas-fit-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 5,
      numReviews: 10,
      detailedDescription: "high quality product",
    },
  ],
};
export default data;
